language: ruby
env:
  global:
    - GIT_REMOTE: git@github.com:captn3m0/tld-a-record.git
addons:
  apt:
    packages:
      # required to avoid SSL errors
      - libcurl4-openssl-dev
      - dnsutils
      - idn
      - python3-dnspython
rvm:
  - 3.0
before_install:
  - openssl aes-256-cbc -K $encrypted_9e883639804e_key -iv $encrypted_9e883639804e_iv -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - eval `ssh-agent -s`
  - ssh-add deploy-key
  - git config user.name "TLD List Bot"
  - git config user.email "tld-bot@captnemo.in"
  # Update bundler: https://docs.travis-ci.com/user/languages/ruby/
  - gem update --system
  - gem install bundler
script:
  - ./scan.sh
  - ./ci.sh
# branch whitelist, only for GitHub Pages
branches:
  except:
    # gh-pages is automatically committed
    - gh-pages
