language: ruby
env:
  global:
  - GIT_REMOTE: git@github.com:captn3m0/tld-a-record.git
addons:
  apt:
    packages:
    # required to avoid SSL errors
    - libcurl4-openssl-dev
    - dnsutils
    - idn
rvm:
- 2.6.3
before_install:
  - openssl aes-256-cbc -K $encrypted_9e883639804e_key -iv $encrypted_9e883639804e_iv -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - eval `ssh-agent -s`
  - ssh-add deploy-key
  - git config user.name "TLD List Bot"
  - git config user.email "tld-bot@captnemo.in"
  # Update bundler: https://docs.travis-ci.com/user/languages/ruby/
  - gem update --system
  - gem install bundler
script:
  - wget "https://data.iana.org/TLD/tlds-alpha-by-domain.txt" --output-document tlds.txt
  - ./scan.sh
  - curl 'https://ipapi.co/yaml/' > website/_data/ip.json
  - echo "This scan was last run on $(date)" >> template.md
  - cp tlds.txt template.md website/
  - ./ci.sh
# branch whitelist, only for GitHub Pages
branches:
  except:
  # gh-pages is automatically committed
  - gh-pages