email: tld@captnemo.in
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: captn3m0
github_username:  captn3m0
title: TLDs with A Records
description: List of TLDs with A Records
theme: jekyll-theme-dinky
markdown: kramdown